[package]
name = "test-with-external-doc"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[dependencies]
doubter = { path = "../..", features = ["external-doc"] }
