[package]
name = "doctest-extract"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[lib]
name = "doctest"
path = "lib.rs"
doc = false

[dependencies]
doubter = { path = "../../doubter" }
