language: rust

branches:
  only:
    - master

cache:
  - cargo: true

env:
  - CARGO_TERM_VERBOSE=true

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt-preview clippy-preview
      script: >-
        cargo fmt -- --check &&
        cargo update &&
        rake test

    - rust: beta
      script: >-
        patch crates/doctest-edition2018/{Cargo.toml,Cargo.toml.patch} &&
        cargo update &&
        rake test test_edition2018

    - rust: nightly
      script: >-
        patch crates/doctest-edition2018/{Cargo.toml,Cargo.toml.patch} &&
        cargo update &&
        rake test test_edition2018 test_nightly
