language: rust

rust:
  - stable
  - beta
  - nightly

branches:
  only:
    - master

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose -p doubter-impl
  - cargo test --verbose -p test-doubter
  - if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then cargo test --verbose -p test-with-external-doc; fi
  - if [[ "${TRAVIS_RUST_VERSION}" = "stable" ]]; then rustup component add rustfmt-preview && cargo fmt -- --check; fi
