language: rust
rust:
  - stable
  - beta
  - nightly
branches:
  only:
    - master
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - if [[ "${TRAVIS_RUST_VERSION}" = "stable" ]]; then rustup component add rustfmt-preview && cargo fmt -- --check; fi
