language: rust

branches:
  only:
    - master

cache:
  - cargo: true

env:
  - CARGO_TERM_VERBOSE=true

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo update && cargo fmt -- --check && rake
    - rust: beta
      script:
        - patch crates/doctest-edition2018/{Cargo.toml,Cargo.toml.patch}
        - cargo update && rake test edition2018_test
    - rust: nightly
      script:
        - cargo update && rake test nightly_test
