[package]
name = "doubter"
version = "0.0.4"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT"
repository = "https://github.com/ubnt-intrepid/doubter.git"
description = "A helper crate for testing Rust code blocks in Markdown"
readme = "README.md"

[workspace]
members = [
  "doubter-impl",
  "crates/doctest",
  "crates/doctest-nightly",
]

[dependencies]
proc-macro-hack = "0.4"
doubter-impl = { version = "0.0.4", path = "doubter-impl" }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[features]
external-doc = ["doubter-impl/external-doc"]
