[package]
name = "doctest-edition2018"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[lib]
name = "doctest"
path = "lib.rs"
doc = false

[dependencies.doubter]
path = "../../doubter"
default-features = false
