name: Doc

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_HUSKY_DONT_INSTALL_HOOKS: true
  CARGO_TERM_VERBOSE: true
  CARGO_NET_OFFLINE: true
  RUST_BACKTRACE: full
  RUSTFLAGS: "--cfg docs"

jobs:
  DeployMasterDoc:
    runs-on: ubuntu-18.04
    container:
      image: rustops/crates-build-env:latest
      options: --memory 3221225472
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Generate Cargo.lock
      uses: actions-rs/cargo@v1
      with:
        command: generate-lockfile
      env:
        CARGO_NET_OFFLINE: false
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Fetch cargo dependencies
      uses: actions-rs/cargo@v1
      with:
        command: fetch
      env:
        CARGO_NET_OFFLINE: false

    # TODO:
    # * restrict all write access expect target/
    - name: Build API docs
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --workspace --no-deps
    - run: rm -fv target/doc/.lock

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: published-docs
        path: target/doc

    - name: Deply to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/doc
